### ISSUE TITLE
请求兼容一下某插件

### ISSUE THREAD

**Issue by hplee0120** [Beginner-Go/luci-app-koolproxyR#2]
尝试过好几个改版KP，（虽然基本都是换皮 比如插件名或是换用规则地址）不过都有一个问题，比如跟SSRP之类有兼容问题，如果打开SSRP类插件的UDP服务器后，国内网络会受影响，例如打开百度贴吧app直接提示网络连接不上。可能是流量优先级的问题？问题应该是当时开发这个插件的作者遗留下来的。请问大佬是否能尝试修复这个历史遗留的兼容问题。

**Comment by Beginner-Go** [comment]
> 尝试过好几个改版KP，（虽然基本都是换皮 比如插件名或是换用规则地址）不过都有一个问题，比如跟SSRP之类有兼容问题，如果打开SSRP类插件的UDP服务器后，国内网络会受影响，例如打开百度贴吧app直接提示网络连接不上。可能是流量优先级的问题？问题应该是当时开发这个插件的作者遗留下来的。请问大佬是否能尝试修复这个历史遗留的兼容问题。

我萌新,这种问题还是另请高就吧

**Comment by hplee0120** [comment]
> > 尝试过好几个改版KP，（虽然基本都是换皮 比如插件名或是换用规则地址）不过都有一个问题，比如跟SSRP之类有兼容问题，如果打开SSRP类插件的UDP服务器后，国内网络会受影响，例如打开百度贴吧app直接提示网络连接不上。可能是流量优先级的问题？问题应该是当时开发这个插件的作者遗留下来的。请问大佬是否能尝试修复这个历史遗留的兼容问题。
> 
> 我萌新,这种问题还是另请高就吧

好吧 大佬客气了，暂时就这样用着吧，不开udp服务器就成😅

**Comment by Beginner-Go** [comment]
> > > 尝试过好几个改版KP，（虽然基本都是换皮 比如插件名或是换用规则地址）不过都有一个问题，比如跟SSRP之类有兼容问题，如果打开SSRP类插件的UDP服务器后，国内网络会受影响，例如打开百度贴吧app直接提示网络连接不上。可能是流量优先级的问题？问题应该是当时开发这个插件的作者遗留下来的。请问大佬是否能尝试修复这个历史遗留的兼容问题。
> > 
> > 
> > 我萌新,这种问题还是另请高就吧
> 
> 好吧 大佬客气了，暂时就这样用着吧，不开udp服务器就成😅

建议这个 [大佬](https://github.com/project-lede/luci-app-godproxy) 的源码

**Comment by hplee0120** [comment]
> > > > 尝试过好几个改版KP，（虽然基本都是换皮 比如插件名或是换用规则地址）不过都有一个问题，比如跟SSRP之类有兼容问题，如果打开SSRP类插件的UDP服务器后，国内网络会受影响，例如打开百度贴吧app直接提示网络连接不上。可能是流量优先级的问题？问题应该是当时开发这个插件的作者遗留下来的。请问大佬是否能尝试修复这个历史遗留的兼容问题。
> > > 
> > > 
> > > 我萌新,这种问题还是另请高就吧
> > 
> > 
> > 好吧 大佬客气了，暂时就这样用着吧，不开udp服务器就成😅
> 
> 建议这个 [大佬](https://github.com/project-lede/luci-app-godproxy) 的源码

一样的，上次尝试过，而且x86编译出来后，规则全部为0，更新也更新不出来。我现在使用比较旧版的koolproxy不带R的，只有静态规则和视频规则那个比较符合我的要求，因为新的这些另添加的规则似乎大部分是按照hosts过滤的，hosts过滤方式不太准误杀也多，或者很多规则根本不符合kp的语法的？有点强行加上的感觉。
